### PR TITLE
Added off-robot folder

### PR DESCRIPTION
**Pull request by arthursiqueira14**
Folder for adding off-robot firmware of projects like ballspeed, motortester, battery status station, etc.

### CODE REVIEW

**Comment by JNeiger** [comment]
Are you looking to get the info reviewed or just add the folder?

**Comment by arthursiqueira14** [comment]
Add the folder

**Comment by Arvind-Srinivasan** [comment]
Is the intent to always use Arduino for off stack projects? Other, then it gets more murky the distinctions in our code base. @kylestach from what I understand, the electrical repo is solely focused on the hardware, firmware has never been put there for boards.

**Comment by kylestach** [comment]
Okay. IMO for smaller projects like this it's just more frustrating to track down the corresponding firmware if it's not in the same place (there becomes an implicit link between repositories that is difficult to keep track of). This gets worse with versioning, abandonment of old projects, etc.

**Comment by Arvind-Srinivasan** [comment]
As discussed during the meeting, this code will be moved to [this repo](https://github.com/RoboJackets/robocup-off-robot-firmware). Thus, closing this PR.

**Pull request closed without merging**
