### PR TITLE
Changes from Competition 2017

### LINKED ISSUE #19: Re-enable robot rx/tx LEDs
Justin disabled them in e8d59dd b/c something related to having too many timers seems to cause the mbed to crash and reboot.

Migrated from RoboJackets/robocup-software#745

### LINKED ISSUE #32: Watchdog triggered by getting stuck in radio receive thread
Robot randomly reboots, suspected to be watchdog triggering after being stuck in one of the radio rx threads and not getting back to main loop. Likely a problem with our implementation of RTOS

### LINKED ISSUE #38: Update base station code.
Base station code is currently broken on jon/stuff which will soon be in master.

### PR DESCRIPTION
**Pull request by jgkamat**
See https://github.com/RoboJackets/robocup-software/pull/1001 for the master issue.

I won't be able to review this, so let me know if you want me to look at other files. I'm going to put @petersonev in charge of this though...

closes #32 
closes #19 
closes #38

### CODE REVIEW

**Comment by jpfeltracco** [comment]
Before this gets merged I'd like to see base station firmware compiling/tested too.

**Comment by jpfeltracco** [comment]
It seems our serial console fault was being caused by filling up too much heap space. Lowering pid windup "fixed" the issue, but being this memory limited is getting a bit ridiculous. 

@ashaw596 lowering windup from 52->30 won't cause major performance issues right?

**Comment by jpfeltracco** [comment]
@petersonev I just put the hot-pluggable radio code into this branch as well. I tested on hardware as well to make sure we didn't break anything in the mean-time.

**Comment by petersonev** [comment]
Not running make pretty before merge because it wants to change a ton of 2011 files which are about to be removed. Will run make pretty after firmware is restructured and 2011 files are removed. For now this needs to be merged into master because the current master doesn't work with our robots and all major problems have been solved on this branch.

**Pull request merged**
