### PR TITLE
Fix Corruption of End of packet

### LINKED ISSUE #50: Fix Corruption at End of RTP Bot to Soccer Packet

### PR DESCRIPTION
**Pull request by ashaw596**
Fix erase iterator to actually erase the last two bytes of the payload instead of the 3rd and 2nd to last.
Fixes #50

### CODE REVIEW

**Comment by guyfleeman** [comment]
@ashaw596 Jeremy is fairly occupied right now but this work in prod/irl right? If so I'm good to merge. @petersonev may have an opinion as well

**Comment by ashaw596** [comment]
It should i think. We tested it with one robot. All 3 repos should be merged at the same time tho.

**Comment by guyfleeman** [comment]
I'll do a merge tonight most likely

**Comment by jpfeltracco** [comment]
Looks good and seems to be working everywhere. Merging.

**Pull request merged**
